layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:categories/:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: sraven0
  mastodon: "@dragon0"
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Python
    web_url: https://www.python.org/
    image_url: https://www.python.org/static/opengraph-icon-200x200.png

  - name: Neovim
    web_url: https://neovim.io/
    image_url: https://neovim.io/logos/neovim-mark.png

  - name: Rust
    web_url: https://www.rust-lang.org/
    image_url: https://www.rust-lang.org/static/images/rust-logo-blk.svg

